# Generated by Django 5.2.6 on 2025-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('party_size', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('seated', 'Seated'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='waiting', max_length=10)),
            ],
        ),
    ]
